name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        - name: install modules
        - run: npm install
        - name: build project
        - run: npm run build
